- name: APT | Import the NodeSource GPG key into APT
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: APT | Add NodeSource deb repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    filename: nodejs
    state: present

- name: APT | Add NodeSource deb-src repository
  apt_repository:
    repo: "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    filename: nodejs
    state: present

- name: APT | Install NodeJS
  apt:
    pkg:
      - nodejs
    state: latest
    update_cache: yes
